In [33]:
import numpy as np
import pandas as pd

from pandas import Series, DataFrame
from sklearn.linear_model import LogisticRegression

In [34]:
bank_full = pd.read_csv('bank_full_w_dummy_vars.csv')
bank_full.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day              ...              job_unknown                   \
0  unknown    5              ...                                         0   
1  unknown    5              ...                                         0   
2  unknown    5              ...                                         0   
3  unknown    5              ...                                         0   
4  unknown    5              ...                                         1   

   job_retired                   job_services                  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   

   job_self_employed             job_unemployed                \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   

  job_maid                     job_student                   \
0                            0                            0   
1                            0                            0   
2                            0                            0   
3                            0                            0   
4                            0                            0   

   married                       single                        \
0                             1                             0   
1                             0                             1   
2                             1                             0   
3                             1                             0   
4                             0                             1   

   divorced                      
0                             0  
1                             1  
2                             0  
3                             0  
4                             1  

[5 rows x 37 columns]

In [36]:
bank_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 37 columns):
age                             45211 non-null int64
job                             45211 non-null object
marital                         45211 non-null object
education                       45211 non-null object
default                         45211 non-null object
balance                         45211 non-null int64
housing                         45211 non-null object
loan                            45211 non-null object
contact                         45211 non-null object
day                             45211 non-null int64
month                           45211 non-null object
duration                        45211 non-null int64
campaign                        45211 non-null int64
pdays                           45211 non-null int64
previous                        45211 non-null int64
poutcome                        45211 non-null object
y                               45

In [37]:
#x_train = bank_full.iloc[:,18:37].values
#x_train

In [38]:
x_train = bank_full.iloc[:,18:37].values
x_train

array([[1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 1, 0, 0],
       ..., 
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [39]:
y_train = bank_full.ix[:,17].values
y_train

C:\Users\Simon\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [40]:
logReg = LogisticRegression()
logReg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [42]:
new_user = [0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1]
new_user = np.array(new_user).reshape(1,-1)
y_pred = logReg.predict(new_user)
y_pred

array([0], dtype=int64)